name: Backend CI Pipeline

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest
    env:
      APP_DIR: app/
      TESTS_DIR: app/test/
      PYTHON_VERSION: 3.9
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Changes On Files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            any:
              - '**'
            app:
              - 'app/**'
      
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        if: steps.changes.outputs.any == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        if: steps.changes.outputs.any == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        if: steps.changes.outputs.app == 'true'
        run: |
          flake8 --show-source --statistics
        working-directory: ${{ env.APP_DIR }}

      - name: Test and Coverage with pytest
        if: s${{ failure() || steps.changes.outputs.any == 'true' }}
        run: |
          pytest --cov-report term --cov=$TESTS_DIR

      - name: Coverage Comment
        if: ${{ failure() || steps.changes.outputs.any == 'true' }}
        id: coverage_comment
        uses: ewjoachim/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}